import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import StoreProvider from "../lib/store-provider";
import { Providers } from "../components/Providers";
const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
        <html lang="en">
          <body className={geist.className}>{children}</body>
        </html>
    </Providers>
  );
}
